"""create_all_tables

Revision ID: 1f59b1b4d28d
Revises: 
Create Date: 2026-06-25 16:24:27.906927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f59b1b4d28d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'USER', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_active_created_at', 'users', ['is_active', 'created_at'], unique=False)
    op.create_table('links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('original_url_hash', sa.String(length=64), nullable=True),
    sa.Column('short_code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('total_clicks', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('unique_clicks', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('last_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('LENGTH(short_code) >= 4 AND LENGTH(short_code) <= 32', name='ch_short_code_length'),
    sa.CheckConstraint('total_clicks >= 0', name='ch_links_total_clicks_nonnegative'),
    sa.CheckConstraint('unique_clicks <= total_clicks', name='ch_links_unique_clicks_lte_total_clicks'),
    sa.CheckConstraint('unique_clicks >= 0', name='ch_links_unique_clicks_nonnegative'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code', name='uq_links_short_code')
    )
    op.create_index('ix_links_active_expires_at', 'links', ['expires_at'], unique=False, postgresql_where=sa.text('is_active = true AND expires_at IS NOT NULL'))
    op.create_index('ix_links_original_url_hash', 'links', ['owner_id', 'original_url_hash'], unique=False)
    op.create_index('ix_links_owner_created_at', 'links', ['owner_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('owner_id IS NOT NULL'))
    op.create_table('clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('visitor_hash', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('referrer', sa.String(length=2048), nullable=True),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('country_code IS NULL OR LENGTH(country_code) = 2', name='ch_clicks_country_code_length'),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clicks_link_country_code', 'clicks', ['link_id', 'country_code'], unique=False)
    op.create_index('ix_clicks_link_created_at', 'clicks', ['link_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_clicks_link_visitor_hash', 'clicks', ['link_id', 'visitor_hash'], unique=False, postgresql_where=sa.text('visitor_hash IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clicks_link_visitor_hash', table_name='clicks', postgresql_where=sa.text('visitor_hash IS NOT NULL'))
    op.drop_index('ix_clicks_link_created_at', table_name='clicks')
    op.drop_index('ix_clicks_link_country_code', table_name='clicks')
    op.drop_table('clicks')
    op.drop_index('ix_links_owner_created_at', table_name='links', postgresql_where=sa.text('owner_id IS NOT NULL'))
    op.drop_index('ix_links_original_url_hash', table_name='links')
    op.drop_index('ix_links_active_expires_at', table_name='links', postgresql_where=sa.text('is_active = true AND expires_at IS NOT NULL'))
    op.drop_table('links')
    op.drop_index('ix_users_active_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

